ALTER TABLE public.wpp_bot_messages 
ADD COLUMN IF NOT EXISTS mediaUrl TEXT,
ADD COLUMN IF NOT EXISTS mediaType TEXT,
ADD COLUMN IF NOT EXISTS fileName TEXT,
ADD COLUMN IF NOT EXISTS isVoice BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS buttons JSONB,
ADD COLUMN IF NOT EXISTS is_direct BOOLEAN DEFAULT false;